[package]
name = "rust_dsa_with_integration_tests"
authors = ["Mighty Donut <mightydonut@proton.me>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
